name: Automated Weekly Update

on:
  push:
    branches:
      - test-actions
  # schedule:
  #    - cron: '0 0 * * 1' # Runs at 00:00 UTC every Monday

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetches all history for all tags and branches
        token: ${{ secrets.PAT }} # Use the renamed PAT here
        ssh-strict: true
        persist-credentials: true
        clean: true
        lfs: false
        submodules: false
        set-safe-directory: true
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Specify your Node.js version
        registry-url: 'https://registry.npmjs.org/'
    
    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install Dependencies
      run: pnpm install

    - name: Update Contracts
      env:
          RONIN_EXPLORER_API_URL: ${{ secrets.RONIN_EXPLORER_API_URL }}
      run: pnpm update-contracts

    - name: Format
      run: pnpm format

    - name: Check for changes
      id: git-check
      run: |
        git diff --quiet && git diff --staged --quiet || echo "::set-output name=changes_detected::true"

    - name: Increment package version
      if: steps.git-check.outputs.changes_detected == 'true'
      run: |
            npm version patch --no-git-tag-version
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PAT }}
        title: '[Automated] Update package version'
        commit-message: 'chore: update package version'
        branch: weekly-update
        delete-branch: true
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        signoff: false
        body: This is an automated pull request to update the package version and publish to npm the latest contracts from the explorer.
        labels: |
          automated pr
        assignees:  |
          alexx855
        reviewers:  |
          alexx855
     - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

    - name: Publish to npm
      if: steps.git-check.outputs.changes_detected == 'true'
      run: pnpm upload
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
